# Generated by Django 4.1.2 on 2022-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
