# Generated by Django 4.1.2 on 2022-11-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('project_slug', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=90)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
