# Generated by Django 4.1.2 on 2022-11-07 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('priority_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Priorities',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('middle_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('telegram_id', models.CharField(max_length=255, null=True)),
                ('vk_id', models.CharField(max_length=255, null=True)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('projects', models.ManyToManyField(to='db_api.project')),
                ('roles', models.ManyToManyField(to='db_api.role')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=90)),
                ('task_slug', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(default='')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_open', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='db_api.user')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performer', to='db_api.user')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_api.priority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_api.project')),
                ('tags', models.ManyToManyField(to='db_api.tag')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
