# Generated by Django 4.1.2 on 2022-11-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0005_user_email_user_middle_name_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, to='db_api.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='db_api.role'),
        ),
    ]
