# Generated by Django 4.1.2 on 2022-11-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0008_rename_middle_name_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='db_api.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='db_api.role'),
        ),
    ]
